siteName: Lojinha
email: erikabelmonte@gmail.com
language: pt-br
about: 
    title: Sobre
    text: |
        Ola! Este eh o site de vendas da Erika e do Tuca.
        
        Este eh o espaco onde anunciamos para venda todos os produtos que compramos para nossa casa e que nao utilizamos mais.
        
        Todos os produtos sao usados, mas em OTIMO estado. A maioria possui, inclusive, nota fiscal.
        
        Damos preferencia para quem comprar e retirar em maos na cidade de Sao Paulo, mas tambem enviamos para todo o Brasil com o frete por conta do comprador.
        
        Em caso de duvidas entrem em contato pelo email ou pelo formulario de contato.
        
        Obrigado! 